"""Auto-generated by tools/build_examples.py from examples/*.lasm.
Do not edit by hand -- edit the .lasm source and re-run the tool.

Each entry is [(opcode, params_bytes), ...], ready for
run_lasm.send_program() -- see run_lasm.py.
"""

PROGRAMS = {
    '01_hello_beep': [
        (0x25, b'\x00\x00\x00\x02\x00'),
        (0x45, b'\x00\x00\x02\x00Q\x05V'),
    ],
    '02_tune': [
        (0x25, b'\x00\x00\x00\x14\x00'),
        (0x45, b'\x00\x00\x14\x00#\xb8\x012C\x02\x14\x00#p\x032C\x02\x14\x00#(\x05P('),
    ],
    '03_loop_forever': [
        (0x25, b'\x00\x00\x00\x08\x00'),
        (0x45, b"\x00\x00\x08\x00Q\x02C\x022\x00'\x88y"),
    ],
    '04_read_sensor': [
        (0x25, b'\x00\x00\x00\x12\x00'),
        (0x45, b"\x00\x00\x12\x002\x00\x03\x85I\x02\x00\x002\x02Q\x04C\x02\x14\x00'\x8f\x9d"),
    ],
    '05_motor_follow': [
        (0x25, b'\x00\x00\x00\x1c\x00'),
        (0x45, b"\x01\x00\x14\x002\x00\x03\x13\x01\x02\x05\x85I\x02\x00\x00(\x04!A'\x04\xe1\x01\xbb"),
        (0x45, b"\x00\x00\x08\x00!\x81C\x02\n\x00'\x95\xad"),
    ],
}
