#!/usr/bin/env python3
"""Compile every examples/*.lasm file into lasm_programs.py, at the
project root -- a small MicroPython-ready module the M5Stick loads
directly (see run_lasm.py).

Runs on the Mac, not the device: lasm_compiler.py needs dataclasses
and pathlib, which stock MicroPython doesn't ship. This is the same
split firmware download already uses -- tools/srec_to_micropython.py
compiles on the Mac, rcx_firmware_data.py is the baked result shipped
to the device. lasm_programs.py plays the same role here.

    python3 tools/build_examples.py

nxt_compatible=False: these examples target a real RCX, not an NXT, so
this compiles opcodes like tmrz to their dedicated RCX bytes rather
than the NXT-firmware substitution lasm_compiler.py defaults to (see
its own module docstring for why that default exists).
"""
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))
import lasm_compiler

EXAMPLES_DIR = _ROOT / "examples"
OUT_PATH = _ROOT / "lasm_programs.py"


def compile_one(path):
    source = path.read_text()
    commands = lasm_compiler.compile_lasm(source, nxt_compatible=False)
    return [(c.opcode, bytes(c.params)) for c in commands]


def main():
    lasm_files = sorted(EXAMPLES_DIR.glob("*.lasm"))
    if not lasm_files:
        print("no .lasm files found in", EXAMPLES_DIR)
        raise SystemExit(1)

    programs = {}
    for path in lasm_files:
        name = path.stem
        try:
            programs[name] = compile_one(path)
        except (lasm_compiler.LasmError, NotImplementedError) as e:
            print("FAILED to compile {}: {}".format(path.name, e))
            raise SystemExit(1)
        print("compiled {}: {} command(s)".format(path.name, len(programs[name])))

    with open(OUT_PATH, "w") as f:
        f.write('"""Auto-generated by tools/build_examples.py from examples/*.lasm.\n')
        f.write('Do not edit by hand -- edit the .lasm source and re-run the tool.\n\n')
        f.write('Each entry is [(opcode, params_bytes), ...], ready for\n')
        f.write('run_lasm.send_program() -- see run_lasm.py.\n"""\n\n')
        f.write("PROGRAMS = {\n")
        for name, cmds in programs.items():
            f.write("    {!r}: [\n".format(name))
            for opcode, params in cmds:
                f.write("        ({:#04x}, {!r}),\n".format(opcode, params))
            f.write("    ],\n")
        f.write("}\n")
    print("wrote", OUT_PATH)


if __name__ == "__main__":
    main()
